### ISSUE TITLE
Illegal Instruction with MULTIPLY_ENABLE=TRUE and DIVIDE_ENABLE=FALSE

### ISSUE THREAD

**Issue by JohannesSpecht** [VectorBlox/orca#11]
I observed that ORCA more or less just ignores divide/modulo instructions from the M extension if HW multiplication is enabled (MULTIPLY_ENABLE=TRUE), but HW division is disabled (DIVIDE_ENABLE=FALSE). It is not raising an exception. However, an exception would be desirable for configurations with partial support of the M extension to emulate the missing pieces in SW.

**Comment by vbx-aseverance** [comment]
We have been putting together a new release which has amongst other things better illegal instruction handling (for complicated business we're currently maintaining an internal repo and GitHub repo, but soon we will switch to working directly from the GitHub repo).  I have exported and pushed our current version to GitHub; let me know if this fixes your issue.

**Comment by JohannesSpecht** [comment]
Thank you for the new version. Unfortunately, no time to review/run simulations right now - sorry. 
If you think the new version allows exception handling under the described setup, feel free to close this issue. I can come back to this once I've time and discover something unexpected.

**Comment by JohannesSpecht** [comment]
Confirmed by simulation, solved (leave the issue closed).
