### ISSUE TITLE
Potential size and performance improvement in full-crt.S

### ISSUE THREAD

**Issue by JohannesSpecht** [VectorBlox/orca#12]
Size and performance of the ISR entry/exit sequence in `full-crt.S` may be improved. The ABI requires only a subset of registers to be saved and restored by the caller - the rest is in the response of the callee or constant (RISC-V Instruction Set Manual, User Level ISA, Version 2.2). The callee in `full-ctr.S` is `handle_exception`, which should likewise follow this convention.
Wouldn't it be sufficient to save 16 registers on the stack (proposed below) instead of 31 (current `full-ctr.S`)?

Proposed new entry sequence (current `full-ctr.S`, lines 29...61):
```
addi sp, sp, -64
sw ra, 60(sp)
sw t0, 56(sp)
sw t1, 52(sp)
sw t2, 48(sp)
sw t3, 44(sp)
sw t4, 40(sp)
sw t5, 36(sp)
sw t6, 32(sp)
sw a0, 28(sp)
sw a1, 24(sp)
sw a2, 20(sp)
sw a3, 16(sp)
sw a4, 12(sp)
sw a5,  8(sp)
sw a6,  4(sp)
sw a7,  0(sp)
```

Proposed new exit sequence (current `full-crt.S`, lines 70...102):
```
lw ra, 60(sp)
lw t0, 56(sp)
lw t1, 52(sp)
lw t2, 48(sp)
lw t3, 44(sp)
lw t4, 40(sp)
lw t5, 36(sp)
lw t6, 32(sp)
lw a0, 28(sp)
lw a1, 24(sp)
lw a2, 20(sp)
lw a3, 16(sp)
lw a4, 12(sp)
lw a5,  8(sp)
lw a6,  4(sp)
lw a7,  0(sp)
addi sp, sp, 64
```
Note: I'm unsure why the disclosed `full-ctr.S` decreases/increases `sp` by 272 on entry/exit instead of 124 (=4*31). The decrement/increment by 64 in the proposed code above may be adjusted accordingly.

**Comment by vbx-aseverance** [comment]
That looks correct; if you have tested this please commit it and issue a pull request.
