### ISSUE TITLE
Fresh clone failed to compile (de2-115)

### ISSUE THREAD

**Issue by douggilliland** [VectorBlox/orca#17]
Using Quartus Prime 18.1.0 Lite.

Tried to compile FPGA (\orca\systems\de2-115) with fresh clone. Got error:

Error (12006): Node instance "rv" instantiates undefined entity "orca_system". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.

Also, got earlier warning (not sure if it is related or not). 

Warning (125092): Tcl Script File orca_system/synthesis/orca_system.qip not found
	Info (125063): set_global_assignment -name QIP_FILE orca_system/synthesis/orca_system.qip

**Comment by vbx-aseverance** [comment]
I am unable to reproduce with Quartus Prime Standard 18.1.1 under Ubuntu
16.04.  I can download Lite 18.1.0 and try, but first can you let me know
your OS and if possible send the QSYS log (synth.orca_system.qsys.log)?

**Comment by douggilliland** [comment]
I am running Windows 7.
There is no file with that name (searched from the root).

**Comment by vbx-aseverance** [comment]
Our scripts were written to run under Linux.  Building under Windows should
be fine but will require manual steps.  The ip/ directory should exist
inside the de2-115 directory but we use a symbolic link under Linux; you
may need to copy it from orca/ip under Windows.  As well you will have to
generate the QSYS system manually (copy either orca_system_cached.qsys or
orca_system_tcm.qsys to orca_system.qsys and open it inside Quartus and
select Generate/Generate HDL) before building the project.

Building software and programming ORCA will likewise likely require manual
steps.  Installing Linux under a virtual machine may be an easier route.

**Comment by douggilliland** [comment]
Oh, OK. Thanks.
