### ISSUE TITLE
mcycle CSR missing

### ISSUE THREAD

**Issue by pagdot** [VectorBlox/orca#19]
The mcycle status register seem to be missing

**Comment by vbx-aseverance** [comment]
Please see the section in the top level readme about the external MTIME(H) counter.  TL;DR is that we have provided an external component and interface because of the requirement that the CSRs must be memory mapped.

**Comment by vbx-aseverance** [comment]
Apologies; I read this at first as being about MTIME.  I have added MCYCLE(H) and MINSTRET(H) registers.
