### ISSUE TITLE
Using Orca with Artix-7

### ISSUE THREAD

**Issue by HARTAOUIMAROUANE** [VectorBlox/orca#21]
hello, I want to implement the Orca CPU on a Artix-7 FPGA. I start with the Zedboard sample and it works perfectly fine. now I want to use the same principle with Artix-7, but I couldn't. if anyone have an idea of how I should start. I will be very thankful.

**Comment by vanjoe** [comment]
Hi, Sorry ORCA is no longer being maintained, feel free to use it, but expect no support.
