### ISSUE TITLE
Vivado bitstream error 

### ISSUE THREAD

**Issue by riscveval** [VectorBlox/orca#5]
Hi when i am trying to run make bitstream from zedboard folder it shows the following error in riscv toolchain
make -C software
make[1]: Entering directory `/home/krradhak/orca/orca/systems/zedboard/software'
riscv32-unknown-elf-gcc -O2 -fno-delete-null-pointer-checks -g -march=rv32im -MD -Wall -std=gnu99 -c main.c -o obj/main.c.o
cc1: error: -march=rv32im: ISA strings must begin with I, RV32I, or RV64I
make[1]: *** [obj/main.c.o] Error 1

 Note :Now Repo not contains riscv-toolchain so can you update riscv-toolchain in Repository and also can you update any tagged release for ORCA.

**Comment by vanjoe** [comment]
It looks like our build-toolchain.sh script got removed at some point, I've re-added it in. It now points to a newer commit where the isa strings have been converted to all lowercase. You will have to re-build with the new script to use the provided makefiles. Alternatively you could hack the makefiles to work with your older toolchain.

**Comment by vanjoe** [comment]
It looks like at some point our build-toolchain script got removed. I've re-added it. It now uses a slightly new version of the tools where the isa strings are lowercase. 

Things should be more stable now that gcc and binutils have been upstreamed, so these incompatibilities shouldn't be such a big deal anymore.

**Comment by riscveval** [comment]
Hi if i am creating Xilinx Project facing issues. So Can you add Xilinx Project similar to Altera Project.

**Comment by rdeiaco** [comment]
Hello,

There is a Xilinx project, it is located under systems/zedboard.

**Comment by riscveval** [comment]
Hi , The make bitstream command only update the bit stream.  Similarly i am asking for make project to create the project first time. 
Note : I am trying to create the project all the files in rtl folder added (Top: orca) but the synthesized resource only contains i/o s no LUT's. So can you share your project.xpr file?

**Comment by rdeiaco** [comment]
Hello,

That's true, `make bitstream` only updates the bitstream. 
However, you can see that `all` depends on `$(OUT_BIT)`, which in turn will generate and build the entire project.
Try just running `make` in the directory, with no arguments, and it should work.

Let me know if this gives you any errors.

**Comment by riscveval** [comment]
Hi, i try to running make all , the following issues occur...
 
ERROR: [Common 17-53] User Exception: Top module not set for synthesis run
Ensure that a valid value is provided for 'top'. The current value for 'top' can be changed using the 'Top Module Name' field under 'Project Settings', or using the 'set_property top' Tcl command

ERROR: [Common 17-70] Application Exception: Top module not set for fileset 'sources_1'. Please ensure that a valid value is provided for 'top'. The value for 'top' can be set/changed using the 'Top Module Name' field under 'Project Settings', or using the 'set_property top' Tcl command (e.g. set_property top <name> [current_fileset]).

**Comment by rdeiaco** [comment]
Hi,

I just did a clean pull and was not able to reproduce your error. Are you running on Windows or Linux?

Did the board design get generated correctly before synthesis? If you open the project in the Vivado GUI, what do you see?
