### ISSUE TITLE
Feature Request:  Debug Module...

### ISSUE THREAD

**Issue by madscientist42** [VectorBlox/orca#6]
Doesn't have to meet the in-progress spec, but it would be really, really nice to have a debug module (since there appears to not be one right now as a result of a skim of the RTL...) for doing code debugging on the target system.

It'd be nice to have On-Chip Debugging...

**Comment by vanjoe** [comment]
Yes, this would be helpful. it is on our radar, but as yet we have no time line for when it will be done.
