### ISSUE TITLE
Error building toolchain with Makefile

### ISSUE THREAD

**Issue by raulgarcia11** [VectorBlox/orca#8]
Hello, 

I executed the "build-toolchain.sh" script to build the toolchain. Then I executed the makefile to build the project for a zedboard. I am using Vivado 2017.1 running on Ubuntu.  Everything works fine except that at the end I get this error:

**make[1]: Entering directory '/home/raul/orca_riscv/orca/systems/zedboard/software'
mkdir -p obj/
riscv32-unknown-elf-gcc -O2 -fno-delete-null-pointer-checks -g -march=rv32im -MD -Wall -std=gnu99 -c main.c -o obj/main.c.o
make[1]: riscv32-unknown-elf-gcc: Command not found
Makefile:28: recipe for target 'obj/main.c.o' failed**
  
Looking into the $RISCV_INSTALL/bin folder where the binaries for the tools should be I can't find gcc. However all the other tools (as, ld, etc) are there. What could be the problem?

**Comment by vanjoe** [comment]
Gcc is built separately from the other tools. Build-toolchain.sh should build them both, but I'd look into the output of that and check for errors there.

**Comment by raulgarcia11** [comment]
There were some missing libraries in my configuration:

configure: error: Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  

I installed, resan the script and now gcc has ben generated. 

Thanks a lot for your help!!

**Comment by vanjoe** [comment]
Glad I could help
